apiVersion: v1
kind: Service
metadata:
  name: kaspa-even-odd-metrics
  namespace: kaspa-even-odd
  labels:
    app.kubernetes.io/name: kaspa-even-odd
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kaspa-even-odd
  ports:
    - name: metrics
      port: 9464
      targetPort: metrics
